basePath: /api/v1/books
definitions:
  ErrorResponseFormat:
    properties:
      code:
        type: integer
      message:
        type: string
      status:
        type: string
    type: object
  model.Book:
    properties:
      authors:
        items:
          type: string
        type: array
      isbn:
        type: string
      pub_date:
        type: string
      publisher:
        type: string
      reg_date:
        type: string
      thumbnail:
        type: string
      title:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: System for register and manage book list
  title: Bookshelf
  version: "1.0"
paths:
  /{code}:
    get:
      description: get book by Code
      parameters:
      - description: Book Code
        in: path
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Book'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponseFormat'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponseFormat'
  /list:
    get:
      description: get total book list
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponseFormat'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponseFormat'
  /search:
    get:
      description: query book info stored in DB
      parameters:
      - description: Search Type
        in: query
        name: target
        required: true
        type: string
      - description: Search String
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponseFormat'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponseFormat'
  /update:
    post:
      description: search book info using book code and store it in DB
      parameters:
      - description: Book Code
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Book'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorResponseFormat'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorResponseFormat'
swagger: "2.0"
